apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    argocd.argoproj.io/instance: app-projects
    holos.run/component.name: app-projects
  name: experiment
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Managed AppProject for Bank of Holos
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
