apiVersion: v1
data:
  ACCOUNTS_DB_URI: postgresql://accounts-admin:accounts-pwd@accounts-db:5432/accounts-db
  POSTGRES_DB: accounts-db
  POSTGRES_PASSWORD: accounts-pwd
  POSTGRES_USER: accounts-admin
kind: ConfigMap
metadata:
  labels:
    app: accounts-db
    application: bank-of-holos
    argocd.argoproj.io/instance: test-bank-accounts-db
    environment: test
    example.com/environment.name: test
    example.com/owner.name: backend
    example.com/tier.name: backend
    holos.run/component.name: test-bank-accounts-db
    team: backend
    tier: backend
  name: accounts-db-config
  namespace: test-bank-backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: test-bank-accounts-db
    environment: test
    example.com/environment.name: test
    example.com/owner.name: backend
    example.com/tier.name: backend
    holos.run/component.name: test-bank-accounts-db
    team: backend
    tier: backend
  name: accounts-db
  namespace: test-bank-backend
spec:
  ports:
  - name: tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: accounts-db
    application: bank-of-holos
    argocd.argoproj.io/instance: test-bank-accounts-db
    environment: test
    example.com/environment.name: test
    example.com/owner.name: backend
    example.com/tier.name: backend
    holos.run/component.name: test-bank-accounts-db
    team: backend
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: test-bank-accounts-db
    environment: test
    example.com/environment.name: test
    example.com/owner.name: backend
    example.com/tier.name: backend
    holos.run/component.name: test-bank-accounts-db
    team: backend
    tier: backend
  name: accounts-db
  namespace: test-bank-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-db
      application: bank-of-holos
      argocd.argoproj.io/instance: test-bank-accounts-db
      environment: test
      example.com/environment.name: test
      example.com/owner.name: backend
      example.com/tier.name: backend
      holos.run/component.name: test-bank-accounts-db
      team: backend
      tier: backend
  serviceName: accounts-db
  template:
    metadata:
      labels:
        app: accounts-db
        application: bank-of-holos
        argocd.argoproj.io/instance: test-bank-accounts-db
        environment: test
        example.com/environment.name: test
        example.com/owner.name: backend
        example.com/tier.name: backend
        holos.run/component.name: test-bank-accounts-db
        team: backend
        tier: backend
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: environment-config
        - configMapRef:
            name: accounts-db-config
        - configMapRef:
            name: demo-data-config
        image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/accounts-db:v0.6.5@sha256:abb955756a82b115e0fd9c5fa1527ae1a744b398b357fd6d7a26348feccad181
        name: accounts-db
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
          subPath: postgres
      serviceAccount: bank-of-holos
      serviceAccountName: bank-of-holos
      volumes:
      - emptyDir: {}
        name: postgresdb
