apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: "true"
  labels:
    app.kubernetes.io/name: httpbin
    argocd.argoproj.io/instance: httpbin
    holos.run/component.name: httpbin
  name: httpbin
spec:
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: httpbin
    argocd.argoproj.io/instance: httpbin
    holos.run/component.name: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: httpbin
    argocd.argoproj.io/instance: httpbin
    holos.run/component.name: httpbin
  name: httpbin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: httpbin
      argocd.argoproj.io/instance: httpbin
      holos.run/component.name: httpbin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httpbin
        argocd.argoproj.io/instance: httpbin
        holos.run/component.name: httpbin
    spec:
      containers:
      - image: mccutchen/go-httpbin
        livenessProbe:
          httpGet:
            path: /status/200
            port: http
        name: httpbin
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /status/200
            port: http
        resources: {}
