apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: namespaces
    app.holos.run/project.name: jeff
    app.holos.run/team.name: platform
    kubernetes.io/metadata.name: jeff
  name: jeff
