apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    stack.example.com/version: v1
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-backend-config
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-backend-config
    owner.example.com/name: backend
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: backend
    team: backend
    tier: backend
  name: bank-of-holos
  namespace: prod-bank-backend
---
apiVersion: v1
data:
  DEMO_LOGIN_PASSWORD: bankofanthos
  DEMO_LOGIN_USERNAME: testuser
  USE_DEMO_DATA: "True"
kind: ConfigMap
metadata:
  annotations:
    stack.example.com/version: v1
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-backend-config
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-backend-config
    owner.example.com/name: backend
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: backend
    team: backend
    tier: backend
  name: demo-data-config
  namespace: prod-bank-backend
---
apiVersion: v1
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: /tmp/.ssh/publickey
kind: ConfigMap
metadata:
  annotations:
    stack.example.com/version: v1
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-backend-config
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-backend-config
    owner.example.com/name: backend
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: backend
    team: backend
    tier: backend
  name: environment-config
  namespace: prod-bank-backend
---
apiVersion: v1
data:
  BALANCES_API_ADDR: balancereader.prod-bank-backend.svc:8080
  CONTACTS_API_ADDR: contacts.prod-bank-backend.svc:8080
  HISTORY_API_ADDR: transactionhistory.prod-bank-backend.svc:8080
  TRANSACTIONS_API_ADDR: ledgerwriter.prod-bank-backend.svc:8080
  USERSERVICE_API_ADDR: userservice.prod-bank-backend.svc:8080
kind: ConfigMap
metadata:
  annotations:
    stack.example.com/version: v1
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-backend-config
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-backend-config
    owner.example.com/name: backend
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: backend
    team: backend
    tier: backend
  name: service-api-config
  namespace: prod-bank-backend
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    stack.example.com/version: v1
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-backend-config
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-backend-config
    owner.example.com/name: backend
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: backend
    team: backend
    tier: backend
  name: jwt-key
  namespace: prod-bank-backend
spec:
  dataFrom:
  - extract:
      key: jwt-key
  refreshInterval: 5s
  secretStoreRef:
    kind: SecretStore
    name: prod-bank-security
  target:
    name: jwt-key
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
    stack.example.com/version: v1
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-backend-config
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-backend-config
    owner.example.com/name: backend
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: backend
    team: backend
    tier: backend
  name: prod-bank-security
  namespace: prod-bank-backend
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: bank-of-holos
      remoteNamespace: prod-bank-security
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
        url: https://kubernetes.default.svc
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  annotations:
    stack.example.com/version: v1
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-backend-config
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-backend-config
    owner.example.com/name: backend
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: backend
    team: backend
    tier: backend
  name: istio-ingress
  namespace: prod-bank-backend
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: istio-ingress
  to:
  - group: ""
    kind: Service
