apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: namespaces
    app.holos.run/project.name: network
    app.holos.run/team.name: platform
    kubernetes.io/metadata.name: istio-ingress
  name: istio-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: namespaces
    app.holos.run/project.name: network
    app.holos.run/team.name: platform
    kubernetes.io/metadata.name: istio-system
  name: istio-system
