apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    holos.run/component.name: bank-secrets
  name: bank-secrets
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: bank-security
  source:
    path: deploy/clusters/local/components/bank-secrets
    repoURL: https://github.com/holos-run/bank-of-holos
    targetRevision: main
