apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    holos.run/component.name: istio-gateway
  name: istio-gateway
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: deploy/clusters/local/components/istio-gateway
    repoURL: https://github.com/holos-run/bank-of-holos
    targetRevision: main
