apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.holos.run/cluster.name: management
    app.holos.run/component.name: namespaces
    app.holos.run/project.name: jeff
    kubernetes.io/metadata.name: jeff
  name: jeff
