apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-projects
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-projects
    owner.example.com/name: security
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: foundation
    team: security
    tier: foundation
  name: prod-bank-backend
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject for Bank of Holos
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-projects
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-projects
    owner.example.com/name: security
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: foundation
    team: security
    tier: foundation
  name: prod-bank-frontend
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject for Bank of Holos
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-projects
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-projects
    owner.example.com/name: security
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: foundation
    team: security
    tier: foundation
  name: prod-bank-security
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject for Bank of Holos
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
