apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: dev-bank-projects
    environment: dev
    example.com/environment.name: dev
    example.com/owner.name: security
    example.com/tier.name: foundation
    holos.run/component.name: dev-bank-projects
    team: security
    tier: foundation
  name: dev-bank-backend
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject for Bank of Holos
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: dev-bank-projects
    environment: dev
    example.com/environment.name: dev
    example.com/owner.name: security
    example.com/tier.name: foundation
    holos.run/component.name: dev-bank-projects
    team: security
    tier: foundation
  name: dev-bank-frontend
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject for Bank of Holos
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    application: bank-of-holos
    argocd.argoproj.io/instance: dev-bank-projects
    environment: dev
    example.com/environment.name: dev
    example.com/owner.name: security
    example.com/tier.name: foundation
    holos.run/component.name: dev-bank-projects
    team: security
    tier: foundation
  name: dev-bank-security
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject for Bank of Holos
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
