apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app: bank
    application: bank-of-holos
    argocd.argoproj.io/instance: prod-bank-routes
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-routes
    owner.example.com/name: security
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: foundation
    team: security
    tier: foundation
  name: bank
  namespace: istio-ingress
spec:
  hostnames:
  - bank.holos.localhost
  parentRefs:
  - name: default
    namespace: istio-ingress
  rules:
  - backendRefs:
    - name: frontend
      namespace: prod-bank-frontend
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
