apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: bank-of-holos
    environment: dev
    environment.example.com/name: dev
    holos.run/component.name: dev-bank-accounts-db
    owner.example.com/name: backend
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: database
    team: backend
    tier: database
  name: dev-bank-accounts-db
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: dev-bank-backend
  source:
    path: examples/environments/deploy/clusters/workload/components/dev-bank-accounts-db
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: demo
