apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: bank-of-holos
    environment: dev
    example.com/environment.name: dev
    example.com/owner.name: security
    example.com/tier.name: security
    holos.run/component.name: dev-bank-secrets
    team: security
    tier: security
  name: dev-bank-secrets
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/clusters/workload/components/dev-bank-secrets
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: main
