apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: bank-of-holos
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-namespaces
    owner.example.com/name: security
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: foundation
    team: security
    tier: foundation
  name: prod-bank-namespaces
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: prod-bank-security
  source:
    path: examples/environments/deploy/clusters/workload/components/prod-bank-namespaces
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: demo
