apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: bank-of-holos
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-frontend
    owner.example.com/name: frontend
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: web
    team: frontend
    tier: web
  name: prod-bank-frontend
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: prod-bank-frontend
  source:
    path: examples/environments/deploy/clusters/workload/components/prod-bank-frontend
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: demo
