apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: bank-of-holos
    environment: prod
    environment.example.com/name: prod
    holos.run/component.name: prod-bank-transaction-history
    owner.example.com/name: backend
    stack.example.com/name: bank-of-holos
    stack.example.com/tier: backend
    team: backend
    tier: backend
  name: prod-bank-transaction-history
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: prod-bank-backend
  source:
    path: examples/environments/deploy/clusters/workload/components/prod-bank-transaction-history
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: demo
