apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    example.com/environment.name: prod
    example.com/owner.name: backend
    holos.run/component.name: prod-bank-backend-config
  name: prod-bank-backend-config
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/clusters/workload/components/prod-bank-backend-config
    repoURL: https://github.com/jeffmccune/bank-of-holos
    targetRevision: main
