apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: argocd
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: dev-bank-backend
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: dev-bank-frontend
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: dev-bank-security
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: network
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: prod-bank-backend
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: prod-bank-frontend
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: prod-bank-security
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: security
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: stage-bank-backend
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: stage-bank-frontend
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: stage-bank-security
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: test-bank-backend
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: test-bank-frontend
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.holos.run/cluster.name: workload
    app.holos.run/component.name: app-projects
    app.holos.run/project.name: argocd
    app.holos.run/team.name: platform
    argocd.argoproj.io/instance: argocd-app-projects
  name: test-bank-security
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Holos managed AppProject
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
